### ISSUE TITLE
Possible ES6-related improvements

### ISSUE THREAD

**Issue by pimotte** [discipl/core#11]
Two small proposals:

- Replace the commonJS export with an ES6 export. 
- Replace the require with a [dynamic import](https://developers.google.com/web/updates/2017/11/dynamic-import)

Both would modernize the code. The dynamic import is not natively supported in firefox and IE (is supported by Chrome/Safari/Edge/NodeJS), but is supported by Babel, so as I see it this shouldn't cause any problems.

**Comment by bkaptijn** [comment]
I agree.

**Comment by pimotte** [comment]
Some initial investigation:

- es6 modules do have native support in node, but it is experimental (both in 10.x and 11.x)
- Using es6 modules with any of the test frameworks (mocha, jasmine) would require using babel, since these don't have native es6 support yet.

**Comment by pimotte** [comment]
Closed with #13
