### ISSUE TITLE
References containing ':' will get cut off

### ISSUE THREAD

**Issue by pimotte** [discipl/core#18]
Due to the way splitLink works, any connector that produces references containing ':' will not work.

Possibilities: 

- Changing splitLink to return splitted[3:].join(DID_DELIMTER)
- Escaping occurences of DID_DELIMITER in references.

**Comment by bkaptijn** [comment]
following the DID specification, references may contain the DID_DELIMITER so it should not get cut off:

splitted[3:].join(DID_DELIMITER) is fine
